#---------------------------
# GitHub Actrion Test1
#
#---------------------------
name: My0GithubActions-Basics

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my_testing:
    runs-on: ubuntu-latest
     
    steps:
      - name: Print Hello Message in Testing
        run: "echo Hello World from Testing"
        
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
      - name: Print Hello Message Deploy
        run: "echo Hello World from job"
