#---------------------------
# GitHub Actrion Test1
#
#---------------------------
name: My0GithubActions-Basics
env:
  APPLICATION_Name : "MyFlask"
  PACKAGE_NAME     : "flask-deploy-file-ver_${{ github.sha }}"
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my_testing:
    runs-on: ubuntu-latest
     
    steps:
      - name: Print Hello Message in Testing
        run: "echo Hello World from Testing"
        
      - name: Execute few commands
        run: 
            echo "Hello Message1"
            echo "Hello Message2"
            echo "Application name:${{ env.APPLICATION_Name }}"
      - name: List current folder
        run : ls -la
      
      - name: Git clone my repo
        uses: actions/chekout@v2
        
      - name: List current folder
        run : ls -la
      
      - name: Lets test some packages of the are here 1
        run : aws --version
  
      - name: Lets test some packages of the are here 2
        run : zip
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
      - name: Print Hello Message Deploy
        run: "echo Hello World from job"
        
      - name: Printing Deployment package
        run : echo "Deploy package name is ${{ env.PACKAGE_NAME }}"
